### ISSUE TITLE
"Convert UDP to TCP"

### ISSUE THREAD

**Issue by serbInit** [MarkoPaul0/DatagramTunneler#12]
I'm coming from the question "https://stackoverflow.com/questions/47208690/convert-udp-to-tcp-ngrok-tcp-udp" where you posted a link to this tool

I'm kinda confused on how to connect to a server

I wan't to forward UDP packages from port 9501 to the client using TCP on port 9502

but I get the error : Could not join multicast group 127.0.0.1:9501. Error 22

Using the commands 

server:
./datagramtunneler --server -i 0.0.0.0 -u 127.0.0.1:9501 -t 9502

client:
./datagramtunneler --client -i 0.0.0.0 -u 127.0.0.1:9501 -t server-public-ip:9502

**Comment by MarkoPaul0** [comment]
Hi @serbInit ,

`127.0.0.1` is not a valid multicast address. Valid multicast addresses range from `224.0.0.0` to `239.255.255.255`. You can find more info [here](https://en.wikipedia.org/wiki/Multicast_address).
