### ISSUE TITLE
Is it going to work with MP TCP?

### ISSUE THREAD

**Issue by mark-stopka** [MarkoPaul0/DatagramTunneler#3]
If I use Datagram Tunneler to take UDP from ntop/n2n full-mesh VPN which is UDP transport only, will n2n be able to use multi-path TCP over several links to increase it's bandwidth? At least in theory?

**Comment by MarkoPaul0** [comment]
I don't have experience with n2n or multipath TCP, however:

* From a quick googling my understanding is that multipath TCP is just another TCP implementation "flavor". The TCP tunneling aspect of the DatagramTunneler should not be affected by the kernel implementation of TCP, whether it be multipath or anything else.
* For the UDP aspect using n2n, I would think it would work as well. If you have UDP data being published somewhere, I don't see why you couldn't use the DatagramTunneler to listen to it and tunnel it.

All in all, I am not a networking expert I can't 100% guarantee that my app would work on some "exotic" network topology I have not tested. If you can, give it a try and please let me know how it goes. It could help future users who read this :).

Let me know if you need any other info, and thanks for trying things out! 👍
