### ISSUE TITLE
Foward data onto a Windows box

### ISSUE THREAD

**Issue by MarkoPaul0** [MarkoPaul0/DatagramTunneler#4]
> "cmd command screen" as in Windows cmd.exe? If so even if you install make and a C++ compiler, you won't be able to compile DatagramTunneler because it is not Windows compatible.

Yes on Windows 10 Pro cmd.exe. Isn't it compatible with Windows? I have been advised for your program to port TCP to UDP for windows. I'm surprized to hear that. How can I solve the issue?

_Originally posted by @BahadirKaya90 in https://github.com/MarkoPaul0/DatagramTunneler/issues/2#issuecomment-506966487_

**Comment by MarkoPaul0** [comment]
@BahadirKaya90, I have created a separate issue because your problem is not related anymore to the ticket you commented on.

**Comment by MarkoPaul0** [comment]
Where were you advised to do that? 

Alright, let's start from the beginning: 
* First, what are you trying to do? 
* I assume CS 1.6 is counter strike?
* Where is the UDP data coming from?
* Where do you want it to go?

It is possible someone implied that things worked on Windows because they were able to tunnel UDP data to a Windows box. HOWEVER, for that to happen you'd still have to use the tunneler on a Linux box.

So let me illustrate this to make it clearer. You can get forwarded UDP data to a windows box, but the tunneler cannot be on a windows box.
```txt
[SOURCE (emits UDP data)] -------------------------------> [TUNNEL BOX A (forwards UDP data via TCP)]
                                                                  |
                                                                  |
                                                                  V
[DESTINATION (listens to fowarded UDP data)] <------------ [TUNNEL BOX B (Publishes UDP data forwarded via TCP)]
```

On the diagram above, both **SOURCE** and **DESTINATION** hosts can be anything you want, (ubuntu, windows, macOs).
However, the **TUNNEL** hosts have to be compatible with the DatagramTunneler, since they are boxes on which you should compile and run a DatagramTunneler instance.

Is this making sense?

**Comment by BahadirKaya90** [comment]
I am advised here. https://teknoltan.com/modem-port-forwarding-acma-yonlendirme-ip-sabitleme/
A Turkish Forum about portforwarding.

Let me explain you from beginning. Yes I want to play Counter Strike 1.6 with buy distant friends over the same server. For this, I need to setup a UDP server and give them my ip address and the UDP port. Normally I can open ports and invite them easily after some Modem configurations. However, My ISP is assigning me an IP address from a system called "CGN" Because of this my friends cannot be able to connect my server.

So, I searched for other possible solutions on the net and found the above website and applied the instructions but for the last step I needed to convert TCP to UDP since the counter strike is on UDP. But it seems there is no way to do that with your compile.

**Comment by BahadirKaya90** [comment]
I have almost no knowledge about such stuff. So it doesn't make sense the above diagram for me. I just came here for this advise but it seems it doesn't work. Thank you for your help and sharing time for me.

**Comment by MarkoPaul0** [comment]
I see. The DatagramTunneler is a tool you can only use if you really know what you are doing. Unfortunately, I can't understand what is said about DatagramTunneler on that forum page so I won't be of much help.

**Comment by BahadirKaya90** [comment]
No problem. Thank you again.

**Comment by Tcmatix** [comment]
Merhabalar Turkcell vın (MF667 Model) kullanıyorum eski türler ancak elimde 4 adet vınn var ve bunları oyun için kullanıyorum  şimdi destek istediğim konu ise şu elimdeki vınların hepsinin manuel olarak ipsini değiştirebiliyorum ve oynadığım oyunda fazla karakter açabiliyorum ancak bu sefer vına ait uygulamaya yani arayüze girdiğimde ise çakışma olduğu için tek biri açılıyor ben ise hepsinin arayüzünü ayrı ayrı açmak istiyorum ve elimdeki vınların hepsinin ipsini manuel olarak yazılım ile sabitlemek istiyorum  bu şekilde yazılım attırmak istiyorum ve nu vınları sıfırlamadığım sürece sabit bir ip olarak kalacağı şekilde ve arayüzlerine ayrı ayrı gireceğim bir şekilde yapmak istiyorum bu konuda yardımcı olur musunuz?
