### ISSUE TITLE
When i Compile i got error 

### ISSUE THREAD

**Issue by TreeV2** [MarkoPaul0/DatagramTunneler#7]
error: variable ‘DatagramTunneler::setupClient(const DatagramTunneler::Config&)::timeval tv’ has initializer but incomplete type
  119 |     struct timeval tv {HEARTBEAT_PERIOD_SEC, 0};
      |                    ^~
src/DatagramTunneler.cpp: In member function ‘void DatagramTunneler::runServer()’:
src/DatagramTunneler.cpp:259:20: error: variable ‘DatagramTunneler::runServer()::timeval tv’ has initializer but incomplete type
  259 |     struct timeval tv {HEARTBEAT_PERIOD_SEC + 1, 0};
      |                    ^~
make: *** [makefile:14: build/DatagramTunneler.o] Error 1

**Comment by TreeV2** [comment]
and can i ask would you add windows  support ?

**Comment by MarkoPaul0** [comment]
Sorry for the late reply. For the compilation error, I would need you to give me more info about your environment. What's OS are you using and what compiler? 

About windows support, unfortunately, it requires Winsocket development which I have never dealt with.

**Comment by TreeV2** [comment]
i am using windows and i am using Cygwin64 Terminal as compiler

**Comment by MarkoPaul0** [comment]
Windows not supported for now.
