### ISSUE TITLE
How would  use this on google colab?

### ISSUE THREAD

**Issue by turtleship69** [MarkoPaul0/DatagramTunneler#9]
My plan is to run a minecraft server on google colab (colab.research.google.com), then use this to route the data elsewhere. What would be the best way to go about doing this?

**Comment by Fisheiyy** [comment]
why are you running a minecraft server on google colab? you can just use ngrok to share your minecraft server to friends

**Comment by turtleship69** [comment]
> why are you running a minecraft server on google colab? you can just use ngrok to share your minecraft server to friends

Bedrock. It uses UDP, which ngrok doesn't support.

**Comment by MarkoPaul0** [comment]
Assuming google colab publishes data to a UDP group let's say 224.10.10.10:
- Have the server-side DT setup so it runs in the same subnet as your google colab, and make it listen to that UDP group.
- Have the client-side DT setup so it runs on whatever other location you want to have the UDP published for other applications to consume and make it connect to your server-DT.
- Any application on the same subnet as the client-side DT can now listen to the same UDP group that was before only accessible to google colab subnet

I know this reply comes ages after the question was asked, but I hope this helps.

**Disclaimer: I have no idea how google colab works or if it actually uses UDP.  So take this reply with a grain of salt.**
